const products = [
  {
    "id": "1",
    "name": "כיפה חלקה עם פס בצבע שחור - דגם 1",
    "image": "1.png",
    "color": "שחור",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 2,
    "description": ""
  },
  {
    "id": "2",
    "name": "כיפה מעורב בצבע טורקיז מעורב - דגם 2",
    "image": "2.png",
    "color": "טורקיז מעורב",
    "diameterCm": "9.6",
    "style": "מעורב",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "3",
    "name": "כיפה חלקה עם פס בצבע כחול כהה - דגם 3",
    "image": "3.png",
    "color": "כחול כהה",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "4",
    "name": "כיפה חלקה עם פס בצבע ירוק כהה - דגם 4",
    "image": "4.png",
    "color": "ירוק כהה",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "5",
    "name": "כיפה חלקה בצבע כחול - דגם 5",
    "image": "5.png",
    "color": "כחול",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "6",
    "name": "כיפה פסים בצבע צהוב ולבן - דגם 6",
    "image": "6.png",
    "color": "צהוב ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "7",
    "name": "כיפה פסים בצבע סגול ולבן - דגם 7",
    "image": "7.png",
    "color": "סגול ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "8",
    "name": "כיפה דוגמה בשוליים בצבע שחור - דגם 8",
    "image": "8.png",
    "color": "שחור",
    "diameterCm": "11",
    "style": "דוגמה בשוליים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "9",
    "name": "כיפה חלקה עם פס בצבע טורקיז - דגם 9",
    "image": "9.png",
    "color": "טורקיז",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "10",
    "name": "כיפה פסים בצבע צבעוני - דגם 10",
    "image": "10.png",
    "color": "צבעוני",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "11",
    "name": "כיפה חלקה בצבע ירוק - דגם 11",
    "image": "11.png",
    "color": "ירוק",
    "diameterCm": "11",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "12",
    "name": "כיפה פסים בצבע חום וצהוב - דגם 12",
    "image": "12.png",
    "color": "חום וצהוב",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "13",
    "name": "כיפה פסים בצבע כחול ולבן - דגם 13",
    "image": "13.png",
    "color": "כחול ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "14",
    "name": "כיפה פסים בצבע ירוק בהיר ולבן - דגם 14",
    "image": "14.png",
    "color": "ירוק בהיר ואפור",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "15",
    "name": "כיפה חלקה בצבע כחול - דגם 15",
    "image": "15.png",
    "color": "כחול",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "16",
    "name": "כיפה פסים בצבע אדום ולבן - דגם 16",
    "image": "16.png",
    "color": "אדום ולבן",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "17",
    "name": "כיפה חלקה בצבע כחול - דגם 17",
    "image": "17.png",
    "color": "כחול",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "18",
    "name": "כיפה דוגמה בשוליים בצבע שחור וכחול - דגם 18",
    "image": "18.png",
    "color": "שחור וכחול",
    "diameterCm": "10",
    "style": "דוגמה בשוליים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "19",
    "name": "כיפה פסים בצבע חום וכחול - דגם 19",
    "image": "19.png",
    "color": "חום וכחול",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "20",
    "name": "כיפה חלקה בצבע תכלת - דגם 20",
    "image": "20.png",
    "color": "תכלת",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "21",
    "name": "כיפה נקודות בצבע ירוק - דגם 21",
    "image": "21.png",
    "color": "ירוק",
    "diameterCm": "10",
    "style": "נקודות",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "22",
    "name": "כיפה פסים עבים בצבע שחור ואדום - דגם 22",
    "image": "22.png",
    "color": "שחור ואדום",
    "diameterCm": "10",
    "style": "פסים עבים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "23",
    "name": "כיפה חלקה עם פס בצבע כחול כהה - דגם 23",
    "image": "23.png",
    "color": "כחול כהה",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "24",
    "name": "כיפה חלקה בצבע תכלת - דגם 24",
    "image": "24.png",
    "color": "תכלת",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "25",
    "name": "כיפה פסים בצבע ירוק מעורב - דגם 25",
    "image": "25.png",
    "color": "ירוק מעורב",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "26",
    "name": "כיפה פסים בצבע לבן צבעוני - דגם 26",
    "image": "26.png",
    "color": "אפור צבעוני",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "27",
    "name": "כיפה חלקה עם פס בצבע שחור וירוק - דגם 27",
    "image": "27.png",
    "color": "שחור וירוק",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "28",
    "name": "כיפה פסים בצבע שחור ולבן - דגם 28",
    "image": "28.png",
    "color": "שחור ולבן",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "29",
    "name": "כיפה פסים בצבע כחול מעורב - דגם 29",
    "image": "29.png",
    "color": "כחול מעורב",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "30",
    "name": "כיפה חלקה בצבע אדום - דגם 30",
    "image": "30.png",
    "color": "אדום עם פס כחול",
    "diameterCm": "9",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "31",
    "name": "כיפה פסים בצבע טורקיז ולבן - דגם 31",
    "image": "31.png",
    "color": "טורקיז ולבן",
    "diameterCm": "12",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "32",
    "name": "כיפה חלקה בצבע ירוק - דגם 32",
    "image": "32.png",
    "color": "ירוק",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "33",
    "name": "כיפה חלקה עם פס בצבע אדום וכחול - דגם 33",
    "image": "33.png",
    "color": "אדום וכחול",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "34",
    "name": "כיפה משבצות בצבע כחול ואפור - דגם 34",
    "image": "34.png",
    "color": "כחול ואפור",
    "diameterCm": "11",
    "style": "משבצות",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "35",
    "name": "כיפה חלקה בצבע כתום - דגם 35",
    "image": "35.png",
    "color": "כתום",
    "diameterCm": "10",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "36",
    "name": "כיפה חלקה עם פס בצבע ירוק ולבן - דגם 36",
    "image": "36.png",
    "color": "ירוק ולבן",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "37",
    "name": "כיפה פסים בצבע ירוק ואפור - דגם 37",
    "image": "37.png",
    "color": "ירוק ואפור",
    "diameterCm": "13",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "38",
    "name": "כיפה פסים בצבע כחול ואדום - דגם 38",
    "image": "38.png",
    "color": "כחול ואדום",
    "diameterCm": "12",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "39",
    "name": "כיפה משבצות בצבע כחול ולבן - דגם 39",
    "image": "39.png",
    "color": "כחול ולבן",
    "diameterCm": "12",
    "style": "משבצות",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "40",
    "name": "כיפה חלקה בצבע ירוק כהה - דגם 40",
    "image": "40.png",
    "color": "ירוק כהה",
    "diameterCm": "11",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "41",
    "name": "כיפה פסים בצבע כחול ולבן - דגם 41",
    "image": "41.png",
    "color": "כחול ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "42",
    "name": "כיפה פסים בצבע שחור ובז' - דגם 42",
    "image": "42.png",
    "color": "שחור ובז'",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "43",
    "name": "כיפה נקודות בצבע אדום ולבן - דגם 43",
    "image": "43.png",
    "color": "אדום ולבן",
    "diameterCm": "11",
    "style": "נקודות",
    "price": 50,
    "stock": 2,
    "description": ""
  },
  {
    "id": "44",
    "name": "כיפה חלקה עם פס בצבע כחול ותכלת - דגם 44",
    "image": "44.png",
    "color": "כחול ותכלת",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "45",
    "name": "כיפה חלקה בצבע אפור כחלחל - דגם 45",
    "image": "45.png",
    "color": "אפור כחלחל",
    "diameterCm": "12",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "46",
    "name": "כיפה חלקה עם פס בצבע טורקיז ואפור - דגם 46",
    "image": "46.png",
    "color": "טורקיז ואפור",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "47",
    "name": "כיפה חלקה עם פס בצבע שחור ואפור - דגם 47",
    "image": "47.png",
    "color": "שחור ואפור",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "48",
    "name": "כיפה מעורב בצבע שחור וכתום - דגם 48",
    "image": "48.png",
    "color": "שחור וכתום",
    "diameterCm": "10",
    "style": "מעורב",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "49",
    "name": "כיפה דוגמה בשוליים בצבע טורקיז - דגם 49",
    "image": "49.png",
    "color": "טורקיז",
    "diameterCm": "10",
    "style": "דוגמה בשוליים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "51",
    "name": "כיפה פסים בצבע סגול ולבן - דגם 51",
    "image": "51.png",
    "color": "סגול ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "52",
    "name": "כיפה פסים בצבע ירוק וצהוב - דגם 52",
    "image": "52.png",
    "color": "ירוק וצהוב",
    "diameterCm": "11",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "53",
    "name": "כיפה פסים בצבע טורקיז ולבן - דגם 53",
    "image": "53.png",
    "color": "טורקיז ולבן",
    "diameterCm": "10",
    "style": "פסים",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "55",
    "name": "כיפה משבצות בצבע ירוק כהה ולבן - דגם 55",
    "image": "55.png",
    "color": "ירוק כהה ולבן",
    "diameterCm": "12",
    "style": "משבצות",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "56",
    "name": "כיפה חלקה בצבע חאקי - דגם 56",
    "image": "56.png",
    "color": "חאקי",
    "diameterCm": "11",
    "style": "חלקה",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "57",
    "name": "כיפה חלקה בצבע חאקי בהיר - דגם 57",
    "image": "57.png",
    "color": "חאקי עם פס אפור",
    "diameterCm": "11",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "58",
    "name": "כיפה חלקה עם פס בצבע שחור וצהוב - דגם 58",
    "image": "58.png",
    "color": "שחור וחאקי",
    "diameterCm": "10",
    "style": "חלקה עם פס",
    "price": 50,
    "stock": 1,
    "description": ""
  },
  {
    "id": "59",
    "name": "כיפה פסים דקים בצבע שחור ולבן - דגם 59",
    "image": "59.png",
    "color": "שחור ולבן",
    "diameterCm": "10",
    "style": "פסים דקים",
    "price": 50,
    "stock": 1,
    "description": ""
  }
];
